all:
	clang++ -Wall -std=c++11 -stdlib=libc++ *.cpp -O3 -o real-time-scheduler
old:
	clang++ -mmacosx-version-min=10.7 -Wall -std=c++11 -stdlib=libc++ *.cpp -O3 -o real-time-scheduler
g++:
	g++ -Wall -std=c++11 *.cpp -O3 -o real-time-scheduler
clean:
	rm -rf real-time-simulator
